# This is an YAML Document to customize the fields that can be chosen for each item
# You can change it as you wish except changing the names of the fields "Types" and "Price"

# YAML Document starts with ---
# Comments start with #

---
Type: # do not change the field name
  - SHIRT
  - PANTS
  - SKIRT
  - JACKET

Size:
  - XS
  - S
  - M
  - L
  - XL

Color:
  - BLACK
  - WHITE
  - RED
  - BLUE
  - GREEN
  - GREY
  - MULTICOLOR

# Fabric:
#   - COTTON
#   - POLYESTER

Price: # do not change the field name
  - 10
  - 20
  - 30
  - 40
  - 50

